### PR TITLE
Modifies footer CSS to make it responsive

### LINKED ISSUE #242: footer is missing on nettest pages
within any of the nettest description pages, the footer is missing:
https://ooni.torproject.org/nettest/

The same footer as on any other page on the website should be incorporated her as well

### PR DESCRIPTION
**Pull request by SaptakS**
Fixes #242 
Refs #284 

The footer is shown in all pages, but in responsive it looks really bad.  So this PR fixes footer.

Also the main and footer combination was a little wonky for responsiveness since footer was made `position: absolute` and were trying to adjust the main by adding a huge padding-bottom. Which I think isn't the best way to go about. 

So I fixed the code so it works more easily without adding style everywhere.

### CODE REVIEW

**Comment by SaptakS** [comment]
cc @p1g30n

**Comment by hellais** [comment]
Does this PR superseed: https://github.com/TheTorProject/ooni-web/pull/284?

**Comment by SaptakS** [comment]
@hellais yes. It fixes what #284 along with some other refactoring. I am happy to resolve conflicts. :)

**Comment by hellais** [comment]
Thanks for resolving the conflicts and for working on this!

This looks good to me. Merging.

**Comment by p1g30n** [comment]
Ah, cool! I only submitted a PR after not being sure if there was a misunderstanding.

**Pull request merged**
