### PR TITLE
Feature/join teams

### PR DESCRIPTION
**Pull request by hellais**
This pull request is related to the registration form for ADINA15.

Here are some screenshots of the GUI.
screen shot 2015-08-05 at 21 19 22
screen shot 2015-08-05 at 21 19 30
screen shot 2015-08-05 at 21 19 45
screen shot 2015-08-05 at 21 19 52
screen shot 2015-08-05 at 21 19 57

Please provide feedback on things that you believe are missing (especially in the form).

@bassosimone @anadahz

### CODE REVIEW

**Comment by hellais** [comment]
Note: The GUI is not yet polished, so please don't focus on aesthetic related comments, but mainly on those pertaining substance.

**Comment by anadahz** [comment]
I think it makes more sense if we reduce the amount of required name fields.
Like 'Username' and 'Real Name'

For the 'Real Name' field a "clause" should be added:
* In order to enter the security team of the Italian parliament  will ask/identify each participant for a valid ID that should match with your given name (make sure your fake ID looks legitimate (: ) .

**Comment by bassosimone** [comment]
To reduce the number of user names requested, maybe we can use the user_name also as screen name for a user?

**Comment by hellais** [comment]
screen shot 2015-08-06 at 17 53 29
screen shot 2015-08-06 at 17 45 55
screen shot 2015-08-06 at 17 45 49
screen shot 2015-08-06 at 17 45 34

**Comment by bassosimone** [comment]
I have no objections to merge this. I tested it yesterday night and it worked. There are graphical issues to be addressed, but I guess we can ameliorate the site in the coming days, but have it online to start off.

**Comment by hellais** [comment]
It's still a bit rough around the edges, but I think this is a sufficient MVP to be ready to deploy.

@bassosimone

**Comment by bassosimone** [comment]
I've tested it again and fixed some minor issues with the commits above. There is still a thing to be fixed: when I register a new team, the number of persons in the team is not propagated, so when I load the list of teams again there is no maximum number of participants specified for that team.

**Comment by bassosimone** [comment]
I fixed the last bug mentioned above. When TheTorProject/ooni-adina15#3 is merged, we can also merge this pull request and proceed with deploying.

**Comment by bassosimone** [comment]
We are now ready to merge.

**Pull request merged**
