### PR TITLE
Added Amharic translation to Ethiopia report

### PR DESCRIPTION
**Pull request by agrabeli**

### CODE REVIEW

**Comment by darkk** [comment]
I can't understand a word, but I'd suggest to give some credits to the translator and/or translating community to make it clear that OONI Team doesn't write amharic (unless anyone does).

**Comment by hellais** [comment]
I wonder if a word better than በኢትዮጵያ could be used, but all in all it looks like a solid translation.

It's good to merge for me.

**Comment by Tafiti** [comment]
@Hellais, what do you mean by ‘better than በኢትዮጵያ could be used’?

**Comment by Tafiti** [comment]
You can credit the translation to ‘Wolete Mariam, Ethiopian translator’.

**Pull request merged**
