### PR TITLE
Post/brazil report translation

### PR DESCRIPTION
**Pull request by anadahz**

### CODE REVIEW

**Comment by anadahz** [comment]
We should find which is the best way to add multilingual posts to the website.

**Comment by hellais** [comment]
Are we still waiting on somebody that speaks Portuguese to review it or is this ready for merge?

**Comment by anadahz** [comment]
@hellais yes we are still waiting for a Portuguese language review.
Any ideas on how to add this nicely to the blog.
Such as having 2 links with two languages in (blog posts) first page [EN], [PT] , and in both blog posts pages `brazil-whatsapp-block-pt.md`, `brazil-whatsapp-block.md` ?

**Comment by anadahz** [comment]
This is ready to be merged.

**Comment by hellais** [comment]
LGTM.

**Pull request merged**
