### PR TITLE
Add partner pages

### PR DESCRIPTION
**Pull request by hellais**
This implements: https://github.com/ooni/ooni.org/issues/273

### CODE REVIEW

**Comment by agrabeli** [comment]
@hellais please replace Digital Society of Zimbabwe's logo because they have re-branded (to "Digital Society of Africa") recently. See: https://www.digitalsociety.africa/ (includes their new logo)

**Comment by agrabeli** [comment]
@hellais Missing partners:

* Tor Project (logo: https://styleguide.torproject.org/brand-assets/)
* Netalitica
* Digital Security Lab Ukraine

**Review by agrabeli — APPROVED** [review]
@hellais I'm done with this page. It now includes all our partners (at least that want to be listed publicly). I've added the missing partners and edited all of the pages. Once you've approved, we can merge and link to this page from the OONI website.

**Comment by agrabeli** [comment]
@hellais In future versions, it would be nice to add a filter or otherwise group the partners by region, so that we can easily, for example, find all the partners from Asia, etc. I'd need to add country codes to each page though so that it can be machine-readable.

**Comment by hellais** [comment]
Moving this into Sprint 22, as I don't have spare cycles to deal with this now.

**Comment by bassosimone** [comment]
Forwarding this issue to Sprint 23.

**Comment by hellais** [comment]
Added the latest logos and masaar. Merging! 🎉

**Pull request merged**
